Repository humanmade/altis-sso, pull requests merged in 2021-07, with the labels that each got.

#54 [docs] Make saml config example consistent with others
  docs/saml-2-0.md
Labels: backport v8-branch

#52 [docs] Update note on SSO hide_native to follow examples
  docs/README.md
Labels: backport v8-branch

#53 [docs] Update config example for consistency
  docs/wordpress.md
Labels: backport v8-branch

#59 Fix port for SAML login
  inc/saml/namespace.php
Labels: backport v5-branch, backport v6-branch, backport v7-branch, backport v8-branch

#64 Allow SAML SSO URLs to function when require login is enabled
  inc/saml/namespace.php
Labels: backport v5-branch, backport v6-branch, backport v7-branch, backport v8-branch

#66 [Backport v7-branch] Allow SAML SSO URLs to function when require login is enabled
  inc/saml/namespace.php
Labels: backport v5-branch, backport v6-branch
